"""The wave-level model still describes the levels it was checked against.

pvz2gardendless/level_model.py is generated by tools/gen_level_model.py and is
what the budget zombie roll (pvz2gardendless/zombie_roll.py) works from. This
suite pins one level per spawn source against values read by hand out of the
game's own level objects at 7840bb0, so a regeneration that silently changes
how a source is read fails here rather than in a player's seed.

If a game update changes one of these levels, re-read the level and update the
expectation. If the extractor changed, the expectation is the thing to believe.
"""
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MODEL = os.path.join(os.path.dirname(HERE), "pvz2gardendless", "level_model.py")

# Loaded by path: importing the package would pull in Archipelago.
spec = importlib.util.spec_from_file_location("level_model", MODEL)
level_model = importlib.util.module_from_spec(spec)
spec.loader.exec_module(level_model)
model = level_model.load()
levels, zombies = model["levels"], model["zombies"]

failed = 0


def fail(msg):
    global failed
    failed += 1
    print("  FAIL  " + msg)


def ok(msg):
    print("  ok    " + msg)


def check(label, got, want):
    if got == want:
        ok(label)
    else:
        fail(f"{label}: got {got!r}, want {want!r}")


def group(level, kind, wave):
    """The first group of that kind in that wave, or None."""
    for g in levels[level]["groups"]:
        if g["k"] == kind and g["w"] == wave:
            return g
    return None


def members(level, kind, wave):
    g = group(level, kind, wave)
    return dict(map(tuple, g["z"])) if g else None


# ── shape ────────────────────────────────────────────────────────────────────

check("the model names the game build it was read from",
      bool(level_model.GAME_DATA_VERSION), True)
check("every tracked level is present", len(levels), 813)

bad = [(lid, g["id"]) for lid, lv in levels.items() for g in lv["groups"]
       if not 1 <= g["w"] <= max(lv["waves"], 1) or any(n <= 0 for _, n in g["z"])]
check("every group sits inside its level's waves with a positive count", bad, [])

unpriced = sorted({n for lv in levels.values() for g in lv["groups"]
                   for n, _ in g["z"] if n not in zombies})
check("every spawned codename has a zombie table entry", unpriced, [])

# ── one level per source ─────────────────────────────────────────────────────

# egypt1 lives inside a Cocos pack file, which the v1 tools never opened.
check("egypt1 (packed) wave 1", members("egypt1", "jittered", 1), {"mummy": 1})
check("egypt1 waves", levels["egypt1"]["waves"], 10)

check("dino8 jittered wave 1", group("dino8", "jittered", 1)["z"], [["dino_armor1", 1]])
check("dino8 jittered wave 1 row", group("dino8", "jittered", 1).get("rows"), [3])
check("dino8 dino event", levels["dino8"]["dinos"][0], [1, "raptor", 2])
check("dino8 stage and plants", (levels["dino8"]["stage"], levels["dino8"]["own_plants"]),
      ("DinoStage", True))

check("pirate8 raiding party, default ZombieType", members("pirate8", "raid", 10),
      {"swashbuckler": 4})
check("pirate8 raiding party count field", group("pirate8", "raid", 10)["f"],
      "SwashbucklerCount")

check("beach12 low tide event", members("beach12", "beach", 2), {"beach_imp": 4})
check("beach12 is bespoke and tidal",
      (levels["beach12"]["bespoke"], levels["beach12"]["tides"]), (True, True))

dark10 = levels["dark10"]["graves"]
check("dark10 initial graves", dark10["initial"],
      {"gravestone_dark": 6, "gravestonePlantfoodOnDestruction": 1})
check("dark10 wave 4 graves", dark10["spawned"][0],
      [4, {"gravestone_dark": 5, "gravestonePlantfoodOnDestruction": 1}])
check("dark10 grave spawner wave 5", members("dark10", "grave_spawn", 5),
      {"dark_armor3": 1, "dark_imp": 2})

check("pirate1 plank rows", levels["pirate1"]["planks"], [0, 1, 3, 4])
check("future14 spider rain", members("future14", "spider", 7), {"future_imp": 6})
check("aloe1 parachute rain", members("aloe1", "parachute", 8), {"lostcity_lostpilot": 4})
check("sky11 dropship imps", members("sky11", "dropship", 4),
      {"sky_dropship": 1, "sky_imp": 3})
# sky10 authors a Wave4DropShipEvent0 that no wave references. The game walks
# Waves only, so it never spawns, and the model must not count it.
check("sky10's unreferenced dropship is not a group", members("sky10", "dropship", 4), None)
check("iceage10 storm", members("iceage10", "storm", 4), {"iceage": 2})
check("egypt5 ground spawner", members("egypt5", "ground", 1),
      {"mummy": 7, "mummy_armor1": 5, "mummy_armor2": 3})

check("egypt7, the camel level, is bespoke", levels["egypt7"]["bespoke"], True)
# The Pirate Seas cannon bonus levels: the player shoots cannons at what flies
# in, so a random zombie there can make the level unwinnable. Each carries
# CannonMinigameProperties, which the bespoke rule matches.
check("the cannon bonus levels are bespoke",
      {lid: levels[lid]["bespoke"] for lid in ("pirate3", "pirate11", "pirate20", "pirate20_1")},
      {"pirate3": True, "pirate11": True, "pirate20": True, "pirate20_1": True})
check("egypt20_1 builds its waves at runtime", levels["egypt20_1"]["generated"], True)

# ── prices ───────────────────────────────────────────────────────────────────

check("mummy effective HP", zombies["mummy"]["hp"], 190)
check("sky_dropship stays excluded", zombies["sky_dropship"]["excluded"], "immobile")
check("gravestone_dark toughness", model["grave_hp"].get("gravestone_dark"), 700)
check("`gravestone` resolves through GridItemTypes", model["grave_hp"].get("gravestone"), 700)
check("kongfu racks toughness", model["grave_hp"].get("kongfu_rack_blade"), 800)

print(f"\n{failed} FAILURE(S)" if failed else "\nLEVEL MODEL OK")
sys.exit(1 if failed else 0)
