"""
PvZ2 Gardendless -- zombie swap tiers for the shuffle_zombies option.

GENERATED by tools/gen_zombie_tiers.py from the game's own data. Do not hand
edit: rerun the generator against a game checkout instead. It also writes
test/data/zombie_balance.json, which test/balance_test.py replays the client's
roll against, so the two cannot describe different tables.

DERIVED FROM GAME DATA, not judgement. Every zombie the shipped levels can
actually spawn is bucketed by properties the game states outright, and a
shuffle only ever trades a zombie for another in its own bucket. Nothing here
is inferred from a name or a world.

The tier key joins these with "-":

  1. `WavePointCost` band -- the game's OWN price for a zombie, what its
     dynamic wave generator spends to field one:
         t1 <= 150   t2 <= 350   t3 <= 650   t4 <= 1000   t5 > 1000
  2. land / water, from `LivesInDeepWater`. Keeping the two apart is what
     stops a swap from putting a zombie in a lane it drowns in.
  3. `garg`, from `ZombieSort == "Gargantuar"`.
  4. A special-mechanic tag, for the zombies that need a specific plant to
     answer them. These are partitioned so a mechanic can never move to a
     world that has no answer for it, and can never vanish from a world whose
     access rule is built on it:
         jester    `MoveSpeedMultiplierWhileJuggling` -- returns your own
                   projectiles. Answered by JESTER_COUNTER_PLANTS, which is
                   what gates Dark Ages.
         iceblock  `NumberOfIceblocksToSpawnWith` -- arrives carrying ice
                   blocks. Answered by FIRE_AURA_PLANTS, which gates
                   Frostbite Caves.
         air       `ChooseToSpawnOnNonDeckRows`, `BalloonToughness` or
                   `BugToughness` -- flies over ground plants. No counter list
                   models this yet, so it is pinned rather than gated.
         blocker   `PlantBlockers` / `ZombieBlockers` /
                   `NumberOfArcadeCabinetsToSpawnWith` -- drops something that
                   specific plants alone can clear.
         shield    `ShieldToughness` / `ProjectileAbsorbingFactor` -- absorbs
                   shots from the front, so a straight shooter stops being an
                   answer.
         summon    `ZombiesToSummon` and friends -- fields zombies of its own,
                   which a level's wave budget never accounted for.
  5. `h{n}`, an effective-HP band: floor(log(hp) / log(1.35)), where hp is
     `Toughness` plus every `StartingArmors` entry's toughness.

     WavePointCost alone was the whole tier key until this band was added, and
     it is a budget price for a generator that re-prices what it fields, not a
     measure of how hard a zombie is to kill. Trading strictly on price held
     per-level cost inside 0.78-1.21 (p5-p95) while per-level HP ran
     0.56-2.51, with 34 levels at 3x or worse -- pirate1 fielded eighteen
     10000 HP shields in place of its basic pirates. With the band, HP lands
     at 0.95-1.05. See ZOMBIE_RANDO_DEV.md.

That fourth partition is the reason this option needs no new access rule.
Threat mechanics cannot be created or destroyed by a shuffle, so every world's
threat footprint after shuffling is exactly the one it had before, and the
plant requirements in WORLD_ENTRY_PLANTS stay exactly as true as they were.

Tiers with a single member simply never swap -- there is nothing comparable
to trade for -- which mirrors how randomize_conveyor_plants leaves a plant
alone when its group has no alternative.

EXCLUSIONS. A codename that is not in the table has no tier, and the client
reads that as "leave this one exactly as the level had it" -- so a level that
ships one still gets it, and no other level can ever gain one:

  camel     every type whose `ZombieBasedOn` contains "camel". A camel is
            not a walker, it is a multi-segment chain driven by
            CamelMinigameProperties, and in the three levels that carry
            that module the camels ARE the game: you match them by hump
            count. Kurt found this in play testing, on egypt7.
            17 types.

  immobile  `WalkSPS` of 0 -- future_infinut_shield (10000 HP),
            future_protector_shield, sky_dropship. These are props, not
            walkers: they never advance, so the lane never clears, and
            the dropship spawns imps for as long as it stands. Priced at
            100-150, so they used to trade with a basic zombie.
            1 type.

  ignored_in_waves `IgnoredInWaves` -- imps and support the game itself
            refuses to wave-spawn, because they are meant to arrive from
            a carrier. Fielding one directly is a thing the game never
            does.
            20 types.

  skycity   `SkyCityShipDetectXOffset` -- Sky City zombies act on the
            airship. In any other world there is no ship to act on.
            14 types.

  unpriced  no `WavePointCost`, so the game gives no answer to "how hard
            is this" and there is nothing to trade on.
            9 types.

Levels a module drives structurally are skipped whole by the client rather
than being handled here: the camel matching games, the cannon levels,
Beghouled, bowling, Last Stand and the other set pieces. See
AP_BESPOKE_MODULES in build_pvzge_ap.py.

259 zombies over 74 tiers, 230 of them (88%) with somebody to trade with.
Worst intra-tier HP ratio 1.33. 61 codenames excluded.
"""

from collections import Counter
from typing import Dict, List

ZOMBIE_TIERS: Dict[str, List[str]] = {
    't1-land-air-h17': [
        'feastivus_swashbuckler', 'lostcity', 'swashbuckler',
    ],  # 3
    't1-land-air-h19': [
        'birthday_jetpack', 'future_jetpack', 'future_jetpack_disco',
    ],  # 3
    't1-land-h0': [
        'chicken', 'chicken_pumpkin',
    ],  # 2
    't1-land-h12': [
        'iceage_weasel',
    ],  # 1
    't1-land-h17': [
        'beach', 'beach_fem', 'birthday', 'cowboy', 'dark', 'dark_imp_dragon',
        'dino', 'easter', 'eighties', 'eighties_8bit', 'feastivus',
        'feastivus_flag', 'foodfight', 'foodfight_flag', 'future',
        'future_flag', 'halloween', 'iceage', 'kongfu_rocket_imp', 'lunar',
        'mummy', 'pirate', 'ra', 'sportzball', 'stpatrick', 'tutorial',
        'valentines',
    ],  # 27
    't1-land-h18': [
        'birthday_pharaoh_inner',
    ],  # 1
    't1-land-h19': [
        'future_flag_veteran', 'lostcity_lostpilot', 'mummy_flag_veteran',
        'pirate_flag_veteran', 'zoybean',
    ],  # 5
    't1-land-h21': [
        'monk_blade',
    ],  # 1
    't1-land-h24': [
        'halloween_flag',
    ],  # 1
    't1-land-shield-h17': [
        'feastivus_poncho_no_plate', 'poncho_no_plate',
    ],  # 2
    't1-land-summon-h17': [
        'kongfu', 'monk',
    ],  # 2
    't1-land-summon-h18': [
        'abbot',
    ],  # 1
    't1-water-h17': [
        'duckytube',
    ],  # 1
    't2-land-air-h17': [
        'lostcity_bug', 'summer_bug',
    ],  # 2
    't2-land-air-h18': [
        'pelican', 'seagull',
    ],  # 2
    't2-land-air-h21': [
        'lostcity_armor1', 'summer_armor1',
    ],  # 2
    't2-land-blocker-h18': [
        'eighties_boombox',
    ],  # 1
    't2-land-h17': [
        'chicken_farmer', 'easter_armor1', 'feastivus_armor1',
        'foodfight_armor1', 'foodfight_gobbler_king', 'iceage_weaselhoarder',
        'lunar_armor1', 'prospector', 'sportzball_armor1', 'stpatrick_armor1',
    ],  # 10
    't2-land-h18': [
        'eighties_breakdancer', 'eighties_mc', 'eighties_punk', 'explorer',
        'kongfu_torch', 'lunar_superfanimp', 'modern_superfanimp',
        'monk_torch',
    ],  # 8
    't2-land-h19': [
        'bobsled_team', 'kongfu_chi', 'lostcity_excavator', 'lostcity_jane',
        'tomb_raiser',
    ],  # 5
    't2-land-h20': [
        'abbot_torch', 'eighties_glitter',
    ],  # 2
    't2-land-h21': [
        'abbot_armor1', 'abbot_fan', 'beach_armor1', 'beach_fem_armor1',
        'birthday_armor1', 'cowboy_armor1', 'dark_armor1', 'dino_armor1',
        'eighties_8bit_armor1', 'eighties_armor1', 'future_armor1',
        'halloween_armor1', 'iceage_armor1', 'kongfu_armor1', 'kongfu_hammer',
        'monk_armor1', 'monk_nunchaku', 'mummy_armor1', 'pirate_armor1',
        'tutorial_armor1', 'valentines_armor1', 'zoybean_armor1',
    ],  # 22
    't2-land-shield-h17': [
        'easter_poncho', 'feastivus_poncho', 'poncho',
    ],  # 3
    't2-land-summon-h18': [
        'kongfu_gong',
    ],  # 1
    't2-water-h19': [
        'beach_snorkel',
    ],  # 1
    't2-water-h21': [
        'duckytube_armor1',
    ],  # 1
    't2-water-h22': [
        'catapult',
    ],  # 1
    't3-land-air-h18': [
        'modern_balloon', 'sportzball_balloon',
    ],  # 2
    't3-land-air-h19': [
        'future_jetpack_veteran',
    ],  # 1
    't3-land-air-h20': [
        'iceage_dodo', 'leprachaun_dodo', 'stpatrick_dodo',
    ],  # 3
    't3-land-air-h21': [
        'lostcity_bug_armor1', 'summer_bug_armor1',
    ],  # 2
    't3-land-air-h22': [
        'lostcity_relichunter',
    ],  # 1
    't3-land-air-h23': [
        'lostcity_armor2', 'lostcity_bug_armor2', 'summer_armor2',
        'summer_bug_armor2',
    ],  # 4
    't3-land-blocker-h20': [
        'eighties_arcade',
    ],  # 1
    't3-land-blocker-h22': [
        'abbot_3section_staff',
    ],  # 1
    't3-land-h17': [
        'barrelroller', 'birthday_barrelroller', 'easter_armor2',
        'feastivus_armor2', 'foodfight_armor2', 'lunar_armor2',
        'sportzball_armor2', 'stpatrick_armor2',
    ],  # 8
    't3-land-h18': [
        'lostcity_crystalskull',
    ],  # 1
    't3-land-h19': [
        'eighties_punk_veteran', 'lostcity_impporter',
    ],  # 2
    't3-land-h20': [
        'kongfu_bomb', 'pirate_captain',
    ],  # 2
    't3-land-h21': [
        'iceage_hunter', 'kongfu_drink', 'monk_drink', 'monk_imp',
    ],  # 4
    't3-land-h22': [
        'feastivus_piano', 'piano',
    ],  # 2
    't3-land-h23': [
        'beach_armor2', 'beach_fem_armor2', 'birthday_armor2',
        'birthday_pharaoh', 'cowboy_armor2', 'dark_armor2', 'dino_armor2',
        'dino_bully', 'eighties_8bit_armor2', 'eighties_armor2',
        'future_armor2', 'halloween_armor2', 'iceage_armor2', 'kongfu_armor2',
        'monk_armor2', 'mummy_armor2', 'pharaoh', 'pharaoh_weak',
        'pirate_armor2', 'tutorial_armor2', 'valentines_armor2', 'west_bull',
    ],  # 22
    't3-land-h24': [
        'abbot_armor2', 'dark_armor3', 'iceage_armor3', 'monk_armor3',
        'zoybean_armor2',
    ],  # 5
    't3-land-h25': [
        'beach_fem_armor4', 'dino_armor3',
    ],  # 2
    't3-land-iceblock-h20': [
        'birthday_troglobite', 'birthday_troglobite_1block',
        'birthday_troglobite_2block', 'iceage_troglobite',
        'iceage_troglobite_1block', 'iceage_troglobite_2block',
    ],  # 6
    't3-land-jester-h20': [
        'birthday_juggler', 'dark_juggler', 'foodfight_chefster',
    ],  # 3
    't3-land-shield-h17': [
        'easter_poncho_plate', 'feastivus_poncho_plate', 'poncho_plate',
    ],  # 3
    't3-land-shield-h21': [
        'abbot_imp',
    ],  # 1
    't3-water-h20': [
        'future_protector',
    ],  # 1
    't3-water-h23': [
        'duckytube_armor2', 'zomboni',
    ],  # 2
    't3-water-h26': [
        'mech_cone',
    ],  # 1
    't4-land-air-h21': [
        'cannon',
    ],  # 1
    't4-land-air-h25': [
        'lostcity_armor4', 'lostcity_bug_armor4',
    ],  # 2
    't4-land-blocker-h19': [
        'beach_surfer',
    ],  # 1
    't4-land-h17': [
        'easter_armor4', 'valentines_armor4',
    ],  # 2
    't4-land-h20': [
        'dark_wizard', 'easter_wizard', 'modern_newspaper',
        'sportzball_wizard',
    ],  # 4
    't4-land-h21': [
        'explorer_veteran', 'monk_drink_veteran',
    ],  # 2
    't4-land-h23': [
        'abbot_chi', 'dark_king', 'iceage_hunter_veteran',
    ],  # 3
    't4-land-h24': [
        'dark_king_veteran', 'west_bull_veteran',
        'west_bull_veteran_plantern_5',
    ],  # 3
    't4-land-h25': [
        'beach_armor4', 'cowboy_armor4', 'dark_armor4', 'dino_armor4',
        'eighties_armor4', 'future_armor4', 'iceage_armor4', 'monk_armor4',
        'mummy_armor4', 'pirate_armor4', 'tutorial_armor4',
    ],  # 11
    't4-land-h26': [
        'abbot_armor4', 'dino_bully_veteran',
    ],  # 2
    't4-land-iceblock-h21': [
        'iceage_troglobite_veteran',
    ],  # 1
    't4-water-h22': [
        'beach_octopus',
    ],  # 1
    't4-water-h23': [
        'beach_fisherman', 'future_protector_veteran',
    ],  # 2
    't4-water-h25': [
        'disco_mech', 'duckytube_armor4', 'football_mech',
    ],  # 3
    't5-land-air-h20': [
        'newspaper_veteran',
    ],  # 1
    't5-land-blocker-h19': [
        'beach_surfer_veteran',
    ],  # 1
    't5-land-h21': [
        'dark_wizard_veteran',
    ],  # 1
    't5-land-h23': [
        'modern_allstar',
    ],  # 1
    't5-water-garg-h20': [
        'easter_gargantuar_af',
    ],  # 1
    't5-water-garg-h27': [
        'beach_gargantuar', 'birthday_gargantuar', 'cowboy_gargantuar',
        'dark_gargantuar', 'easter_gargantuar', 'egypt_gargantuar',
        'eighties_gargantuar', 'feastivus_gargantuar', 'future_gargantuar',
        'halloween_gargantuar', 'holiday_gargantuar', 'iceage_gargantuar',
        'lostcity_gargantuar', 'pirate_gargantuar', 'sportzball_gargantuar',
        'summer_gargantuar', 'tutorial_gargantuar', 'valentines_gargantuar',
        'zoybean_gargantuar',
    ],  # 19
    't5-water-garg-h28': [
        'dino_gargantuar', 'kongfu_bronze_hook', 'kongfu_bronze_strong',
    ],  # 3
    't5-water-garg-summon-h28': [
        'kongfu_bronze_chi', 'kongfu_bronze_chi_without_torch',
    ],  # 2
    't5-water-h25': [
        'sky_dronemaker',
    ],  # 1
}

# codename -> effective HP (Toughness plus every StartingArmors entry). Sent to
# the client as slot_data so its per-level budget guard can weigh a level's
# roster before and after a shuffle; see ZOMBIE_RANDO_DEV.md. Only the tiered
# zombies are here -- an untiered one never moves, so nothing needs to weigh
# it.
ZOMBIE_HP: Dict[str, int] = {
    'abbot': 250,
    'abbot_3section_staff': 900,
    'abbot_armor1': 620,
    'abbot_armor2': 1350,
    'abbot_armor4': 2450,
    'abbot_chi': 1100,
    'abbot_fan': 550,
    'abbot_imp': 600,
    'abbot_torch': 500,
    'barrelroller': 190,
    'beach': 190,
    'beach_armor1': 560,
    'beach_armor2': 1290,
    'beach_armor4': 2390,
    'beach_fem': 190,
    'beach_fem_armor1': 560,
    'beach_fem_armor2': 1290,
    'beach_fem_armor4': 2390,
    'beach_fisherman': 1000,
    'beach_gargantuar': 3600,
    'beach_octopus': 910,
    'beach_snorkel': 350,
    'beach_surfer': 350,
    'beach_surfer_veteran': 350,
    'birthday': 190,
    'birthday_armor1': 560,
    'birthday_armor2': 1290,
    'birthday_barrelroller': 190,
    'birthday_gargantuar': 3600,
    'birthday_jetpack': 380,
    'birthday_juggler': 420,
    'birthday_pharaoh': 1200,
    'birthday_pharaoh_inner': 290,
    'birthday_troglobite': 470,
    'birthday_troglobite_1block': 470,
    'birthday_troglobite_2block': 470,
    'bobsled_team': 390,
    'cannon': 600,
    'catapult': 750,
    'chicken': 1,
    'chicken_farmer': 190,
    'chicken_pumpkin': 1,
    'cowboy': 190,
    'cowboy_armor1': 560,
    'cowboy_armor2': 1290,
    'cowboy_armor4': 2390,
    'cowboy_gargantuar': 3600,
    'dark': 190,
    'dark_armor1': 560,
    'dark_armor2': 1290,
    'dark_armor3': 1790,
    'dark_armor4': 2390,
    'dark_gargantuar': 3600,
    'dark_imp_dragon': 190,
    'dark_juggler': 420,
    'dark_king': 1000,
    'dark_king_veteran': 1500,
    'dark_wizard': 490,
    'dark_wizard_veteran': 630,
    'dino': 190,
    'dino_armor1': 560,
    'dino_armor2': 1290,
    'dino_armor3': 1990,
    'dino_armor4': 2390,
    'dino_bully': 1100,
    'dino_bully_veteran': 2470,
    'dino_gargantuar': 5400,
    'disco_mech': 2000,
    'duckytube': 190,
    'duckytube_armor1': 560,
    'duckytube_armor2': 1290,
    'duckytube_armor4': 2390,
    'easter': 190,
    'easter_armor1': 190,
    'easter_armor2': 190,
    'easter_armor4': 190,
    'easter_gargantuar': 3600,
    'easter_gargantuar_af': 500,
    'easter_poncho': 190,
    'easter_poncho_plate': 190,
    'easter_wizard': 490,
    'egypt_gargantuar': 3600,
    'eighties': 190,
    'eighties_8bit': 190,
    'eighties_8bit_armor1': 560,
    'eighties_8bit_armor2': 1290,
    'eighties_arcade': 490,
    'eighties_armor1': 560,
    'eighties_armor2': 1290,
    'eighties_armor4': 2390,
    'eighties_boombox': 250,
    'eighties_breakdancer': 250,
    'eighties_gargantuar': 3600,
    'eighties_glitter': 490,
    'eighties_mc': 250,
    'eighties_punk': 250,
    'eighties_punk_veteran': 400,
    'explorer': 250,
    'explorer_veteran': 650,
    'feastivus': 190,
    'feastivus_armor1': 190,
    'feastivus_armor2': 190,
    'feastivus_flag': 190,
    'feastivus_gargantuar': 3600,
    'feastivus_piano': 840,
    'feastivus_poncho': 190,
    'feastivus_poncho_no_plate': 190,
    'feastivus_poncho_plate': 190,
    'feastivus_swashbuckler': 190,
    'foodfight': 190,
    'foodfight_armor1': 190,
    'foodfight_armor2': 190,
    'foodfight_chefster': 420,
    'foodfight_flag': 190,
    'foodfight_gobbler_king': 190,
    'football_mech': 2000,
    'future': 190,
    'future_armor1': 560,
    'future_armor2': 1290,
    'future_armor4': 2390,
    'future_flag': 190,
    'future_flag_veteran': 350,
    'future_gargantuar': 3600,
    'future_jetpack': 380,
    'future_jetpack_disco': 380,
    'future_jetpack_veteran': 390,
    'future_protector': 500,
    'future_protector_veteran': 1000,
    'halloween': 190,
    'halloween_armor1': 560,
    'halloween_armor2': 1290,
    'halloween_flag': 1790,
    'halloween_gargantuar': 3600,
    'holiday_gargantuar': 3600,
    'iceage': 190,
    'iceage_armor1': 560,
    'iceage_armor2': 1290,
    'iceage_armor3': 1790,
    'iceage_armor4': 2390,
    'iceage_dodo': 490,
    'iceage_gargantuar': 3600,
    'iceage_hunter': 700,
    'iceage_hunter_veteran': 1100,
    'iceage_troglobite': 470,
    'iceage_troglobite_1block': 470,
    'iceage_troglobite_2block': 470,
    'iceage_troglobite_veteran': 700,
    'iceage_weasel': 40,
    'iceage_weaselhoarder': 190,
    'kongfu': 190,
    'kongfu_armor1': 560,
    'kongfu_armor2': 1290,
    'kongfu_bomb': 500,
    'kongfu_bronze_chi': 4700,
    'kongfu_bronze_chi_without_torch': 4700,
    'kongfu_bronze_hook': 5500,
    'kongfu_bronze_strong': 6000,
    'kongfu_chi': 300,
    'kongfu_drink': 600,
    'kongfu_gong': 250,
    'kongfu_hammer': 600,
    'kongfu_rocket_imp': 190,
    'kongfu_torch': 250,
    'leprachaun_dodo': 490,
    'lostcity': 190,
    'lostcity_armor1': 560,
    'lostcity_armor2': 1290,
    'lostcity_armor4': 2390,
    'lostcity_bug': 190,
    'lostcity_bug_armor1': 560,
    'lostcity_bug_armor2': 1290,
    'lostcity_bug_armor4': 2390,
    'lostcity_crystalskull': 250,
    'lostcity_excavator': 350,
    'lostcity_gargantuar': 3600,
    'lostcity_impporter': 350,
    'lostcity_jane': 350,
    'lostcity_lostpilot': 350,
    'lostcity_relichunter': 760,
    'lunar': 190,
    'lunar_armor1': 190,
    'lunar_armor2': 190,
    'lunar_superfanimp': 270,
    'mech_cone': 2500,
    'modern_allstar': 1100,
    'modern_balloon': 250,
    'modern_newspaper': 460,
    'modern_superfanimp': 270,
    'monk': 190,
    'monk_armor1': 560,
    'monk_armor2': 1290,
    'monk_armor3': 1790,
    'monk_armor4': 2390,
    'monk_blade': 600,
    'monk_drink': 600,
    'monk_drink_veteran': 600,
    'monk_imp': 600,
    'monk_nunchaku': 600,
    'monk_torch': 270,
    'mummy': 190,
    'mummy_armor1': 560,
    'mummy_armor2': 1290,
    'mummy_armor4': 2390,
    'mummy_flag_veteran': 350,
    'newspaper_veteran': 490,
    'pelican': 270,
    'pharaoh': 1200,
    'pharaoh_weak': 1200,
    'piano': 840,
    'pirate': 190,
    'pirate_armor1': 560,
    'pirate_armor2': 1290,
    'pirate_armor4': 2390,
    'pirate_captain': 420,
    'pirate_flag_veteran': 350,
    'pirate_gargantuar': 3600,
    'poncho': 190,
    'poncho_no_plate': 190,
    'poncho_plate': 190,
    'prospector': 190,
    'ra': 190,
    'seagull': 270,
    'sky_dronemaker': 2000,
    'sportzball': 190,
    'sportzball_armor1': 190,
    'sportzball_armor2': 190,
    'sportzball_balloon': 250,
    'sportzball_gargantuar': 3600,
    'sportzball_wizard': 490,
    'stpatrick': 190,
    'stpatrick_armor1': 190,
    'stpatrick_armor2': 190,
    'stpatrick_dodo': 490,
    'summer_armor1': 560,
    'summer_armor2': 1290,
    'summer_bug': 190,
    'summer_bug_armor1': 560,
    'summer_bug_armor2': 1290,
    'summer_gargantuar': 3600,
    'swashbuckler': 190,
    'tomb_raiser': 380,
    'tutorial': 190,
    'tutorial_armor1': 560,
    'tutorial_armor2': 1290,
    'tutorial_armor4': 2390,
    'tutorial_gargantuar': 3600,
    'valentines': 190,
    'valentines_armor1': 560,
    'valentines_armor2': 1290,
    'valentines_armor4': 190,
    'valentines_gargantuar': 3600,
    'west_bull': 1300,
    'west_bull_veteran': 1400,
    'west_bull_veteran_plantern_5': 1400,
    'zomboni': 1100,
    'zoybean': 300,
    'zoybean_armor1': 670,
    'zoybean_armor2': 1400,
    'zoybean_gargantuar': 4000,
}

# Why each dropped codename is dropped, kept so a test can assert the reasons
# still hold after a regeneration rather than trusting this file.
ZOMBIE_EXCLUSIONS: Dict[str, List[str]] = {
    'camel': [
        'camel_manyhump', 'camel_manyhump_touch', 'camel_onehump',
        'camel_onehump_touch', 'camel_threehump', 'camel_threehump_touch',
        'camel_twohump', 'camel_twohump_touch', 'easter_camel_manyhump',
        'easter_camel_onehump', 'easter_camel_twohump',
        'feastivus_camel_manyhump', 'feastivus_camel_onehump',
        'feastivus_camel_twohump', 'lunar_camel_manyhump',
        'lunar_camel_onehump', 'lunar_camel_twohump',
    ],  # 17
    'ignored_in_waves': [
        'beach_imp', 'dark_imp', 'dino_imp', 'easter_imp', 'egypt_imp',
        'eighties_imp', 'feastivus_imp', 'future_imp', 'halloween_imp',
        'holiday_imp', 'iceage_imp', 'leprachaun_imp', 'lostcity_imp',
        'pirate_imp', 'sky_imp', 'sportzball_imp', 'stpatrick_imp',
        'summer_imp', 'tutorial_imp', 'west_bullrider',
    ],  # 20
    'immobile': [
        'sky_dropship',
    ],  # 1
    'skycity': [
        'sky', 'sky_arbiterx', 'sky_armor1', 'sky_armor2', 'sky_battleplane',
        'sky_electric', 'sky_flag', 'sky_gargantuar',
        'sky_gargantuar_armor2_thrower', 'sky_twin', 'sky_twin_upper',
        'sky_unarmed', 'sky_unarmed_armor1', 'sky_unarmed_armor2',
    ],  # 14
    'unpriced': [
        'chicken_ge', 'lawn', 'lawn_armor1', 'lawn_armor2', 'lawn_armor3',
        'lawn_armor4', 'lawn_gargantuar', 'lawn_imp', 'sky_dronemaker_alt',
    ],  # 9
}

# codename -> tier key. The client is sent ZOMBIE_TIERS and inverts it the same
# way; this side needs it to answer "may these two zombies trade places".
ZOMBIE_TIER_OF: Dict[str, str] = {
    zombie: tier for tier, zombies in ZOMBIE_TIERS.items() for zombie in zombies
}

# A zombie may not appear in two tiers -- the dict comprehension above would
# silently keep the last one, and the client's swap pool would disagree with
# this side's about which trade is legal.
_seen = Counter(z for zombies in ZOMBIE_TIERS.values() for z in zombies)
_dupes = sorted(z for z, n in _seen.items() if n > 1)
if _dupes:
    raise ValueError(f"zombies listed in more than one tier: {_dupes}")

# Tiers whose special-mechanic tag means the game needs a specific plant to
# answer them. Kept as a name list rather than folded into the tier keys so a
# test can assert the partition still holds after a data regeneration.
THREAT_TAGS = ("jester", "iceblock", "air", "blocker", "shield", "summon")

# Geometric width of one HP band, as the generator used it. A test reads this
# to assert no tier spans more than one band's worth of HP.
HP_BAND = 1.35


def tier_of(zombie: str) -> str:
    """Tier key for a zombie codename, or "" if it is not shuffled at all."""
    return ZOMBIE_TIER_OF.get(zombie, "")


def swap_pool(zombie: str) -> List[str]:
    """Zombies this one may be traded for, itself included.

    Empty for a zombie outside the table -- a Zomboss, a camel, a prop, a type
    no shipped level spawns -- which the caller reads as "leave this one
    exactly as the level had it".
    """
    tier = ZOMBIE_TIER_OF.get(zombie)
    return list(ZOMBIE_TIERS[tier]) if tier else []
